spring:
    data:
      web:
        pageable:
            default-page-size: 25
            max-page-size: 100
    application:
        name: especificacoes
    datasource:
        url: jdbc:postgresql://jotanunes-db-get-info-database.b.aivencloud.com:21733/jotanunesdb?sslmode=require
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            maximum-pool-size: 10
            minimum-idle: 1
            idle-timeout: 60000
            max-lifetime: 600000
            connection-timeout: 30000
    jpa:
        properties:
            hibernate:
                ddl-auto: none
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
        open-in-view: false
    flyway:
        enabled: true
        baseline-on-migrate: true
logging:
    level:
      root: WARN
---
spring:
    config:
      activate:
          on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/jotanunesdb?stringtype=unspecified
        username: ${DEV_DB_USERNAME}
        password: ${DEV_DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                ddl-auto: validate
        open-in-view: false
    flyway:
        enabled: true
        clean-disabled: false
logging:
    level:
      root: INFO

