# Perfil de produção
spring:
    data:
      web:
        pageable:
            default-page-size: 25
            max-page-size: 100
    application:
        name: especificacoes
    datasource:
        url: jdbc:postgresql://jotanunes-db-get-info-database.b.aivencloud.com:21733/jotanunesdb?sslmode=require
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            maximum-pool-size: 10
            minimum-idle: 1
            idle-timeout: 60000
            max-lifetime: 600000
            connection-timeout: 30000
    jpa:
        properties:
            hibernate:
                ddl-auto: none
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
        open-in-view: false
    flyway:
        enabled: true
        baseline-on-migrate: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_SENHA}
      properties:
        mail:
          transport:
            protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
        test-connection: true
logging:
    level:
      root: WARN


#Config do serviço de geração de documentos no ambiente de produção
app:
    docs:
        node-command: node
        project-path: /app/docx-gen
        script-name: gerar-doc-api.js
        timeout-seconds: 30
        max-concurrent: 5

---
# Perfil de desenvolvimento(dev)
spring:
    config:
      activate:
          on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/jotanunesdb?stringtype=unspecified
        username: ${DEV_DB_USERNAME}
        password: ${DEV_DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                ddl-auto: validate
        open-in-view: false
    flyway:
        enabled: true
        clean-disabled: false
logging:
    level:
        root: INFO
        org.hibernate.SQL: DEBUG
        com.jotanunes.especificacoes.service.com.jotanunes.especificacoes.service.DocGenerateService: DEBUG

# Config do serviço de geração de documentos no ambiente de desenvolvimento
app:
    docs:
        node-command: C:/Program Files/nodejs/node.exe
        project-path: ./docx-gen

