spring:
    application:
        name: especificacoes
    datasource:
        url: jdbc:postgresql://localhost:5432/jotanunesdb
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                ddl-auto: none
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
    flyway:
        enabled: true
        baseline-on-migrate: true



