spring:
    application:
        name: especificacoes
    datasource:
        url: jdbc:postgresql://jotanunes-db-get-info-database.b.aivencloud.com:21733/jotanunesdb?sslmode=require
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                ddl-auto: none
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
    flyway:
        enabled: true
        baseline-on-migrate: true

---
spring:
    config:
      activate:
          on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/jotanunesdb?stringtype=unspecified
        username: ${DEV_DB_USERNAME}
        password: ${DEV_DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                ddl-auto: validate
    flyway:
        enabled: true
        clean-disabled: false

