server {
    listen 80;
    server_name jotanunes-backend.duckdns.org;
    
    # Força redirecionamento para HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name jotanunes-backend.duckdns.org;

    # Caminhos exatos que o Certbot gerou
    ssl_certificate /etc/letsencrypt/live/jotanunes-backend.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jotanunes-backend.duckdns.org/privkey.pem;

    location / {
        # O nome "especificacoes-app" é o nome do serviço no docker-compose abaixo
        proxy_pass http://especificacoes-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
