package com.jotanunes.especificacoes.enums;

public enum Permissoes {
    CRIAR_EMPREENDIMENTOS,
    EDITAR_EMPREENDIMENTOS,
    DESATIVAR_EMPREENDIMENTOS,
    REVISAR_EMPREENDIMENTOS,
    POPULAR_CATALOGOS,
    LISTAR_USUARIOS,
    CRIAR_USUARIOS,
    EDITAR_USUARIOS,
    DESATIVAR_USUARIOS,
    DELETAR_USUARIOS

}
